# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.1.0
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  install-node:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '18.16'
      - run: node --version
# Orchestrate jobs using workflows
  test:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    working_directory: ~/repo
    steps:
      - checkout
      - run: pnpm install
      - run: pnpm test
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  test:
    jobs:
      - install-node
      - node/test:
          test-results-for: jest


